language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - source ./configure
  - make

script:
  - make O0.out
  # - ./O1.out
  # - ./O2.out
  # - ./O3.out
